# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher', :branch => 'ios9'
  pod 'MCIKit', :git =>'https://github.com/merci-app/mcikit-podspec', :tag => "1.5.1"
  pod 'MarketPlaceKit', :git =>'https://github.com/merci-app/marketplacekit-podspec', :tag => "1.0.6"
  pod 'PayKit', :git =>'https://github.com/merci-app/paykit-podspec', :tag => "1.0.6"
  pod 'WithdrawalKit', :git =>'https://github.com/merci-app/withdrawalkit-podspec', :tag => "1.0.6"

end
